version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-stretch-node
    steps:
      - checkout
      - run: gem install bundler:2.2.6
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ad:36:06:b7:9b:89:84:f5:5c:e2:42:b2:76:c5:5b:23" #上記メモったハッシュを指定
      - run: ssh -p $stockapp.pem ec2-user@3.114.40.165 "cd /var/www/rails/stockapp/"
 
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:   #buildジョブが完了されるまで処理が待機されるように設定
            - build
          filters:
            branches:
              only: master
  # build-and-deploy:
  #   jobs:
  #     - aws-ecr/build_and_push_image:
  #         account-url: "685226300427.dkr.ecr.us-west-2.amazonaws.com"
  #         repo: "${AWS_RESOURCE_NAME_PREFIX}"
  #         region: us-west-2
  #         tag: "${CIRCLE_SHA1}"
  #     - aws-ecs/deploy-service-update:
  #         requires:
  #           - aws-ecr/build_and_push_image
  #         aws-region: us-west-2
  #         family: "${AWS_RESOURCE_NAME_PREFIX}-service"
  #         cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
  #         container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"     
