version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-stretch-node
    steps:
      - checkout
      - run: gem install bundler:1.3.0
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ad:36:06:b7:9b:89:84:f5:5c:e2:42:b2:76:c5:5b:23" #上記メモったハッシュを指定
      - run: ssh -p $stockapp.pem ec2-user@3.114.40.165 "cd /var/www/rails/stockapp/"
 
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
      - filters:
        branches:
          only: circlecl
  deploy-web:
    jobs:
      - aws-ecr/build-and-push-image:
        filters:
          branches:
            only: 
        account-url: 3.114.40.165
        create-repo: true
        repo: "$stockapp_web"
        region:
        tag:
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: "nginx-rails-app2"
          cluster-name:  "nginx-rails"
          service-name: "ecs-rails"
          container-image-name-updates: 'container=web,image-and-tag=$/$stockapp_web:${CIRCLE_SHA1}'
  deploy-app:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          create-repo: true
          dockerfile: docker/Dockerfile
          repo: "${APP_NAME}_app"
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: "nginx-rails-app2"
          cluster-name: "nginx-rails"
          service-name: "ecs-rails"
          container-image-name-updates:  'container=app,image-and-tag=${AWS_ECR_ACCOUNT_URL}/${APP_NAME}_app:${CIRCLE_SHA1}'      
